// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: resilience.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResilienceService_Stream_FullMethodName = "/resilience.ResilienceService/Stream"
)

// ResilienceServiceClient is the client API for ResilienceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResilienceService provides a bidirectional streaming ping/pong exchange
// between client and server.  Both endpoints send messages continuously at
// configurable intervals and log every send/receive.
type ResilienceServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BidirectionalStreamRequest, BidirectionalStreamResponse], error)
}

type resilienceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResilienceServiceClient(cc grpc.ClientConnInterface) ResilienceServiceClient {
	return &resilienceServiceClient{cc}
}

func (c *resilienceServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BidirectionalStreamRequest, BidirectionalStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResilienceService_ServiceDesc.Streams[0], ResilienceService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BidirectionalStreamRequest, BidirectionalStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilienceService_StreamClient = grpc.BidiStreamingClient[BidirectionalStreamRequest, BidirectionalStreamResponse]

// ResilienceServiceServer is the server API for ResilienceService service.
// All implementations must embed UnimplementedResilienceServiceServer
// for forward compatibility.
//
// ResilienceService provides a bidirectional streaming ping/pong exchange
// between client and server.  Both endpoints send messages continuously at
// configurable intervals and log every send/receive.
type ResilienceServiceServer interface {
	Stream(grpc.BidiStreamingServer[BidirectionalStreamRequest, BidirectionalStreamResponse]) error
	mustEmbedUnimplementedResilienceServiceServer()
}

// UnimplementedResilienceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResilienceServiceServer struct{}

func (UnimplementedResilienceServiceServer) Stream(grpc.BidiStreamingServer[BidirectionalStreamRequest, BidirectionalStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedResilienceServiceServer) mustEmbedUnimplementedResilienceServiceServer() {}
func (UnimplementedResilienceServiceServer) testEmbeddedByValue()                           {}

// UnsafeResilienceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResilienceServiceServer will
// result in compilation errors.
type UnsafeResilienceServiceServer interface {
	mustEmbedUnimplementedResilienceServiceServer()
}

func RegisterResilienceServiceServer(s grpc.ServiceRegistrar, srv ResilienceServiceServer) {
	// If the following call panics, it indicates UnimplementedResilienceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResilienceService_ServiceDesc, srv)
}

func _ResilienceService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResilienceServiceServer).Stream(&grpc.GenericServerStream[BidirectionalStreamRequest, BidirectionalStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResilienceService_StreamServer = grpc.BidiStreamingServer[BidirectionalStreamRequest, BidirectionalStreamResponse]

// ResilienceService_ServiceDesc is the grpc.ServiceDesc for ResilienceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResilienceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resilience.ResilienceService",
	HandlerType: (*ResilienceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ResilienceService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "resilience.proto",
}
