// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: resilience.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidirectionalStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          *Ping                  `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidirectionalStreamRequest) Reset() {
	*x = BidirectionalStreamRequest{}
	mi := &file_resilience_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidirectionalStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStreamRequest) ProtoMessage() {}

func (x *BidirectionalStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resilience_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStreamRequest.ProtoReflect.Descriptor instead.
func (*BidirectionalStreamRequest) Descriptor() ([]byte, []int) {
	return file_resilience_proto_rawDescGZIP(), []int{0}
}

func (x *BidirectionalStreamRequest) GetPing() *Ping {
	if x != nil {
		return x.Ping
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_resilience_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_resilience_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_resilience_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ping) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_resilience_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_resilience_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_resilience_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pong) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

// Error is emitted by the server in response to a Ping to simulate an error
// surfacing on an already-established stream. The id must match the request.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_resilience_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_resilience_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_resilience_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type BidirectionalStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BidirectionalStreamResponse_Pong
	//	*BidirectionalStreamResponse_Error
	Payload       isBidirectionalStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidirectionalStreamResponse) Reset() {
	*x = BidirectionalStreamResponse{}
	mi := &file_resilience_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidirectionalStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStreamResponse) ProtoMessage() {}

func (x *BidirectionalStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resilience_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStreamResponse.ProtoReflect.Descriptor instead.
func (*BidirectionalStreamResponse) Descriptor() ([]byte, []int) {
	return file_resilience_proto_rawDescGZIP(), []int{4}
}

func (x *BidirectionalStreamResponse) GetPayload() isBidirectionalStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BidirectionalStreamResponse) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*BidirectionalStreamResponse_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *BidirectionalStreamResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*BidirectionalStreamResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isBidirectionalStreamResponse_Payload interface {
	isBidirectionalStreamResponse_Payload()
}

type BidirectionalStreamResponse_Pong struct {
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type BidirectionalStreamResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*BidirectionalStreamResponse_Pong) isBidirectionalStreamResponse_Payload() {}

func (*BidirectionalStreamResponse_Error) isBidirectionalStreamResponse_Payload() {}

var File_resilience_proto protoreflect.FileDescriptor

const file_resilience_proto_rawDesc = "" +
	"\n" +
	"\x10resilience.proto\x12\n" +
	"resilience\"B\n" +
	"\x1aBidirectionalStreamRequest\x12$\n" +
	"\x04ping\x18\x01 \x01(\v2\x10.resilience.PingR\x04ping\".\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\".\n" +
	"\x04Pong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\"E\n" +
	"\x05Error\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"{\n" +
	"\x1bBidirectionalStreamResponse\x12&\n" +
	"\x04pong\x18\x01 \x01(\v2\x10.resilience.PongH\x00R\x04pong\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.resilience.ErrorH\x00R\x05errorB\t\n" +
	"\apayload2r\n" +
	"\x11ResilienceService\x12]\n" +
	"\x06Stream\x12&.resilience.BidirectionalStreamRequest\x1a'.resilience.BidirectionalStreamResponse(\x010\x01B(Z&github.com/example/grpc-resilience/apib\x06proto3"

var (
	file_resilience_proto_rawDescOnce sync.Once
	file_resilience_proto_rawDescData []byte
)

func file_resilience_proto_rawDescGZIP() []byte {
	file_resilience_proto_rawDescOnce.Do(func() {
		file_resilience_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resilience_proto_rawDesc), len(file_resilience_proto_rawDesc)))
	})
	return file_resilience_proto_rawDescData
}

var file_resilience_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_resilience_proto_goTypes = []any{
	(*BidirectionalStreamRequest)(nil),  // 0: resilience.BidirectionalStreamRequest
	(*Ping)(nil),                        // 1: resilience.Ping
	(*Pong)(nil),                        // 2: resilience.Pong
	(*Error)(nil),                       // 3: resilience.Error
	(*BidirectionalStreamResponse)(nil), // 4: resilience.BidirectionalStreamResponse
}
var file_resilience_proto_depIdxs = []int32{
	1, // 0: resilience.BidirectionalStreamRequest.ping:type_name -> resilience.Ping
	2, // 1: resilience.BidirectionalStreamResponse.pong:type_name -> resilience.Pong
	3, // 2: resilience.BidirectionalStreamResponse.error:type_name -> resilience.Error
	0, // 3: resilience.ResilienceService.Stream:input_type -> resilience.BidirectionalStreamRequest
	4, // 4: resilience.ResilienceService.Stream:output_type -> resilience.BidirectionalStreamResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resilience_proto_init() }
func file_resilience_proto_init() {
	if File_resilience_proto != nil {
		return
	}
	file_resilience_proto_msgTypes[4].OneofWrappers = []any{
		(*BidirectionalStreamResponse_Pong)(nil),
		(*BidirectionalStreamResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resilience_proto_rawDesc), len(file_resilience_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resilience_proto_goTypes,
		DependencyIndexes: file_resilience_proto_depIdxs,
		MessageInfos:      file_resilience_proto_msgTypes,
	}.Build()
	File_resilience_proto = out.File
	file_resilience_proto_goTypes = nil
	file_resilience_proto_depIdxs = nil
}
