# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resilience.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'resilience.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10resilience.proto\x12\nresilience\"<\n\x1a\x42idirectionalStreamRequest\x12\x1e\n\x04ping\x18\x01 \x01(\x0b\x32\x10.resilience.Ping\"\"\n\x04Ping\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\"\"\n\x04Pong\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\"2\n\x05\x45rror\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"n\n\x1b\x42idirectionalStreamResponse\x12 \n\x04pong\x18\x01 \x01(\x0b\x32\x10.resilience.PongH\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.resilience.ErrorH\x00\x42\t\n\x07payload2r\n\x11ResilienceService\x12]\n\x06Stream\x12&.resilience.BidirectionalStreamRequest\x1a\'.resilience.BidirectionalStreamResponse(\x01\x30\x01\x42(Z&github.com/example/grpc-resilience/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resilience_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/example/grpc-resilience/api'
  _globals['_BIDIRECTIONALSTREAMREQUEST']._serialized_start=32
  _globals['_BIDIRECTIONALSTREAMREQUEST']._serialized_end=92
  _globals['_PING']._serialized_start=94
  _globals['_PING']._serialized_end=128
  _globals['_PONG']._serialized_start=130
  _globals['_PONG']._serialized_end=164
  _globals['_ERROR']._serialized_start=166
  _globals['_ERROR']._serialized_end=216
  _globals['_BIDIRECTIONALSTREAMRESPONSE']._serialized_start=218
  _globals['_BIDIRECTIONALSTREAMRESPONSE']._serialized_end=328
  _globals['_RESILIENCESERVICE']._serialized_start=330
  _globals['_RESILIENCESERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
